# Generated by Django 4.2.23 on 2025-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Sobrenome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('DataDeNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('RG', models.CharField(max_length=20, unique=True)),
                ('Endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('Bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('Cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('Estado', models.CharField(blank=True, max_length=20, null=True)),
                ('CEP', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
