# Generated by Django 4.2.23 on 2025-09-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='Pessoa',
            new_name='pessoa',
        ),
    ]
