# Generated by Django 4.2.23 on 2025-09-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0002_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='CEP',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='DataDeNascimento',
            new_name='datadenascimento',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='RG',
            new_name='rg',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Sobrenome',
            new_name='sobrenome',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='Telefone',
            new_name='telefone',
        ),
    ]
